# Generated by Django 2.0.3 on 2018-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoltArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_diam', models.IntegerField(verbose_name='Диаметр болта')),
                ('bolt_ab', models.FloatField(verbose_name='Площадь болта Ab')),
                ('bolt_bn', models.FloatField(verbose_name='Площадь болта Abn')),
            ],
            options={
                'verbose_name_plural': 'Площадь болта',
                'verbose_name': 'значение в таблицу',
                'db_table': 'Площадь болта',
            },
        ),
        migrations.CreateModel(
            name='ResCrushing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_run', models.IntegerField(verbose_name='Сопротивление Run')),
                ('cls_a', models.IntegerField(verbose_name='Значение для класса А')),
                ('cls_bc', models.IntegerField(verbose_name='начение для класса BC')),
            ],
            options={
                'verbose_name_plural': 'Сопротивление на срез',
                'verbose_name': 'значение в таблицу',
                'db_table': 'Сопротивление на срез',
            },
        ),
        migrations.CreateModel(
            name='ResShear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolt_class', models.CharField(max_length=10, verbose_name='Класс прочности болта')),
                ('bolt_rbs', models.IntegerField(verbose_name='Сопротивление Rbs')),
                ('bolt_rbt', models.IntegerField(verbose_name='Сопротивление Rbt')),
            ],
            options={
                'verbose_name_plural': 'Сопротивление на растяжение и смятие',
                'verbose_name': 'значение в таблицу',
                'db_table': 'Сопротивление на растяжение и смятие',
            },
        ),
        migrations.CreateModel(
            name='StallMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_mark', models.CharField(max_length=200, verbose_name='Марка стали')),
                ('stall_run', models.IntegerField(verbose_name='Сопротивление Run')),
            ],
            options={
                'verbose_name_plural': 'Марка стали',
                'verbose_name': 'значение в таблицу',
                'db_table': 'Марка стали',
            },
        ),
    ]
